Update VPN_Script

diff --git a/VPN_Script b/VPN_Script
--- a/VPN_Script
+++ b/VPN_Script
@@ -5,7 +5,7 @@
 
 
 die() {
-        echo $'\e[1;34m[-]Error: Oops, your account number seems to be wron \e[0m'  $1" >&2
+        echo $'\e[1;34m'[-]Error: Oops, your account number seems to be wron$'\e[0m'  $1" >&2
 
         exit 1
 }
